# upload the script and set the remote host to a subnode

- name: upload the subnode script
  become: yes
  copy:
    src: ./subnode2.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the subnode script
  become: yes
  shell: /home/ubuntu/subnode2.sh
