- name: upload the docker-compose requirement script1
  become: yes
  copy:
    src: ./docker-compose.yml
    dest: /home/ubuntu/
    mode: 0777

- name: upload the docker-compose requirement script2
  become: yes
  copy:
    src: ./Dockerfile
    dest: /home/ubuntu/
    mode: 0777
    
- name: upload the docker-compose requirement script3
  become: yes
  copy:
    src: ./requirements.txt
    dest: /home/ubuntu/
    mode: 0777
   
- name: upload the webnode script
  become: yes
  copy:
    src: ./webnode.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the webnode script
  become: yes
  shell: /home/ubuntu/webnode.sh