- name: upload the proxy setting script
  become: yes
  copy:
    src: ./proxy.sh
    dest: /home/ubuntu/
    mode: 0777

- name: upload the proxy conf script
  become: yes
  copy:
    src: ./http-proxy.conf
    dest: /home/ubuntu/
    mode: 0777

- name: execute the proxy setting script
  become: yes
  shell: /home/ubuntu/proxy.sh

- name: Set proxy to be accessible externally
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
  with_items:
    - 'HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/'
    - 'HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/'
    - 'http_proxy=http://wwwproxy.unimelb.edu.au:8000/'
    - 'https_proxy=http://wwwproxy.unimelb.edu.au:8000/'
    - 'no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au'
