# Create an instance on NeCTAR

- name: Create an instance0 for data collection
  os_server:
    name: 'instance0'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: 'volume0'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: instance0

- debug:
    msg: "Instance0 has been created. IP address is {{ instance0.openstack.public_v4 }}"
  when: instance0.openstack is defined

- name: Create an instance1 for data collection
  os_server:
    name: 'instance1'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: 'volume1'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: instance1

- debug:
    msg: "Instance1 has been created. IP address is {{ instance1.openstack.public_v4 }}"
  when: instance1.openstack is defined

- name: Create an instance2 for data collection
  os_server:
    name: 'instance2'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: 'volume2'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: instance2

- debug:
    msg: "Instance2 has been created. IP address is {{ instance2.openstack.public_v4 }}"
  when: instance2.openstack is defined

- name: Create an instance as web server
  os_server:
    name: 'instance3'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ web_instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ wsg_names }}'
    volumes: 'volume3'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: instance3

- debug:
    msg: "Instance3 has been created. IP address is {{ instance3.openstack.public_v4 }}"
  when: instance3.openstack is defined